scrape_configs:
  - job_name: vault
    metrics_path: /v1/sys/metrics
    params:
      format: ['prometheus']
    scheme: http
    authorization:
      credentials_file: /etc/prometheus/prometheus-token
    consul_sd_configs:
    - server: 'http://10.0.0.194:8500'
      services:
        - 'vault-server'
    #static_configs:
    #- targets: ['10.0.0.194:8200']
